### ISSUE TITLE
Metadata is not correct properly since update to v.0.5.0

### ISSUE THREAD

**Issue by l-emele** [OpenEnergyPlatform/oeplatform#444] opened 2019-10-09 07:15 UTC
Since the update of the platform to version 0.5.0 metadata of some tables is not displayed correctly.

Examples are:

https://openenergy-platform.org/dataedit/view/model_draft/ego_grid_pf_hv_result_line

![grafik](https://user-images.githubusercontent.com/36884905/66459337-22f3ff80-ea75-11e9-844c-cdbca0fc6d72.png)

https://openenergy-platform.org/dataedit/view/scenario/ksz2050_r2_ams2012_electricity_consumption

![grafik](https://user-images.githubusercontent.com/36884905/66459362-2dae9480-ea75-11e9-9ea2-d78bdbf47a8b.png)

**Comment by christian-rli** [comment] 2019-10-09 07:36
@Bachibouzouk is currently working on support for display of metadata version 1.4.0. I'm not sure if this is related, but there might lie a few issues like this ahead of us for a short while. But in the end it should work like a charm 🌈

**Comment by Bachibouzouk** [comment] 2019-10-11 10:43
> @Bachibouzouk & @4lm are currently working on support for display of metadata version 1.4.0 (see #427 / #441 ). I'm not sure if this is related, but there might lie a few issues like this ahead of us for a short while. But in the end it should work like a charm rainbow

It is not related since our current changes are not merged into master, and therefore cannot affect the current version.

However I can say that this is the display one gets when there is an error in during the loading of the  metadata form the database.

Hopefully #441 will fix this problem!

**Comment by l-emele** [comment] 2020-05-11 15:04
In the current version of the OEP the display of metadata has improved but still does not work properly. Parts of the metadata get truncated at the right side, even if there is still enough space:

![grafik](https://user-images.githubusercontent.com/36884905/81577210-75015880-93a9-11ea-957f-0bb7fce9c44c.png)

**Comment by christian-rli** [comment] 2021-12-01 13:22
I believe the display is now without the error you created a screenshot of @l-emele . At least I am unable to reproduce. Can you confirm this? If so, you may close the issue :)

**Closed** 2022-02-23 15:03 UTC
Labels: bug, SzenarienDB
