### ISSUE TITLE
Login fails with user reset mail referring to example.com

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/oeplatform#1301] opened 2023-07-11 14:52 UTC
## Description of the issue

As reported by @carstenhoyerklick the login attempt to an OEP account has failed and a password reset mail was sent with a link to example.com Maybe @carstenhoyerklick can elaborate.

## Steps to Reproduce
1.Don't know how to reproduce

## Ideas of solution

Look into how sending the mail containing example.com is triggered and figure out what caused the problem.

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment] 2023-07-12 08:49
We have already discussed this bug in the last oep-dev meeting. At the end of the month the next release is planned with which this bug will be fixed.

Edit
I suspect that it is due to an incorrect setting in the django setting. In this respect, the error can also be fixed earlier.

**Comment by carstenhoyerklick** [comment] 2023-07-12 08:53
I could work around it, by manually copying the URL into the browser and replacing exemple.com by openenergy-platoform.org. I looks like, there is a wrong domain at some place.

**Comment by jh-RLI** [comment] 2023-07-12 09:52
Yes, that is correct. We introduced the [django sites framework](https://docs.djangoproject.com/en/3.2/ref/contrib/sites/) which interferes with the domain in our settings. It basically sets the `example.com` by default. Since there is no regression testing for the email, this went unnoticed for a few months.

**Comment by jh-RLI** [comment] 2023-07-25 11:16
@adelmemariani & me will execute this on the production OEP as part of the upcoming release on friday. 

> I could reproduce the error and found a solution that works on my machine, using the django shell (python manage.py shell):
> 
> ```python
> from django.contrib.sites.models import Site
> mysite = Site.objects.get_current()
> mysite.domain = 'openenergyplatform.org'
> mysite.name = 'Open Energy Platform'
> mysite.save()
> ```

**Comment by jh-RLI** [comment] 2023-07-28 13:11
This is now fixed on the https://openenergy-platform.org/

**Closed by jh-RLI** 2023-07-28 13:11 UTC
Labels: bug
