### ISSUE TITLE
adding tags with umlauts end up with truncated keywords

### ISSUE THREAD

**Issue by wingechr** [OpenEnergyPlatform/oeplatform#972] opened 2022-05-11 11:13 UTC
i.e. adding `Öko-Institute` adds keyword `ko_institute`

**Comment by jh-RLI** [comment] 2022-05-18 12:34
also noticed this: i think in the first place it is related to the [regex when normalizing the tag name](https://github.com/OpenEnergyPlatform/oeplatform/blob/dd22a23dc061eeea8d280b82274d04854bb341f3/dataedit/structures.py#L54), and also it  might be that I mixed something up and now a new tag is created using the normalized name as tag name.

**Comment by wingechr** [comment] 2022-05-20 08:00
yea, the keyword are the normalized names, which they should not

**Comment by jh-RLI** [comment] 2022-05-20 08:57
I will fix this soon.

**Comment by jh-RLI** [comment] 2022-05-20 15:04
@wingechr  The problem is that through the regex the normalized name of the tags with umlauts can occur twice e.g. `Öko `becomes `ko `and `Üko` also becomes `ko`. Im not suer what the best solution for this would be, we could check for [these ](https://stackoverflow.com/questions/22017723/regex-for-umlaut) at least and try to make umlauts lowercase. Generally, the problem is fixed by d80d64df6a5b2665e250d28edf371a996ae25dba

**Closed** 2022-06-07 12:43 UTC
