### ISSUE TITLE
Translate German text on contact page

### ISSUE THREAD

**Issue by l-emele** [OpenEnergyPlatform/oeplatform#442] opened 2019-10-08 15:32 UTC
On the [contact page](https://openenergy-platform.org/contact/) there is some German text to be translated to English:
> Oder nutzen Sie das Issue-System auf GitHub.

**Comment by Bachibouzouk** [comment] 2019-10-21 14:09
@l-emele - Write in the PR which closes the issue "Closes #<issue number>" this way the issue is closed automatically when one merge the changes. Right now the issue was marked as solved but the changes are not yet incorporated. I reopen the issue now so that it can be closed automatically.

**Closed** 2019-10-21 14:10 UTC
