### ISSUE TITLE
help text behave funny

### ISSUE THREAD

**Issue by MGlauer** [OpenEnergyPlatform/oeplatform#51] opened 2016-03-21 09:13 UTC
Fields are class attributes of the corresponding model. Changes on one instance will be done on all. Find another way to change help texts on instances Energyframework.

**Comment by christian-rli** [comment] 2021-11-01 10:11
Help texts are working. Please specify why a change is actually needed. Closing, because cannot reproduce a bug. Feel free to reopen if you think it's necessary.

**Closed by christian-rli** 2021-11-01 10:11 UTC
Labels: bug, specification_sheet
