### ISSUE TITLE
Bug OEP Scenario Factsheets

### ISSUE THREAD

**Issue by Izzet91** [OpenEnergyPlatform/oeplatform#455] opened 2019-11-07 12:48 UTC
@Bachibouzouk 
it's not possible to open the Scenario Factsheets on OEP

**Comment by 4lm** [comment] 2019-11-07 15:54
Duplicate of: https://github.com/OpenEnergyPlatform/oeplatform/issues/445

**Closed by 4lm** 2019-11-07 15:54 UTC
Labels: bug, duplicate
