### ISSUE TITLE
toep: cannot edit / delete study

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#679] opened 2020-11-10 10:30 UTC
http://toep.iks.cs.ovgu.de/factsheets/studies/1/edit/
Same happens on the live OEP. It would be good to be able to edit/delete scenarios and studies. 
This may involve adding a 'delete' button somewhere. Not sure whether this exists already.

**Comment by Ludee** [comment] 2021-01-07 09:52
This is quite important since the Scenario Factsheets are essential for SzenarienDB. Is this already fixed for the next release?

**Comment by christian-rli** [comment] 2021-12-01 14:51
duplicate of #595

**Closed by christian-rli** 2021-12-01 14:51 UTC
Labels: bug, SzenarienDB
