### ISSUE TITLE
"Download CSV" and "Download View" return slightly different results.

### ISSUE THREAD

**Issue by jh-RLI** [OpenEnergyPlatform/oeplatform#935] opened 2022-03-10 12:59 UTC
As @l-emele noted in #933, the download functions download CSV and download view (after filtering data from a table) return slightly different results:

> Also I noticed that the structure of the downloaded CSV files differ slightly. In the file from the "Download CSV" button, the entries in the `id` column are in quotations marks (showing here only the header and the first tow data rows):
> ```
> "id","variable","energy_carrier","unit","year","value"
> "1","Primary energy consumption","Nuclear","PJ","2020","728.3828459388"
> "2","Primary energy consumption","Nuclear","PJ","2030","0.0"
> ```
> 
> In the partial download via "Download view", the are no quotation marks in this columns:
> ```
> "id","variable","energy_carrier","unit","year","value"
> 1,"Primary energy consumption","Nuclear","PJ",2020,"728.3828459388"
> 2,"Primary energy consumption","Nuclear","PJ",2030,"0.0"
> ```

**Comment by wingechr** [comment] 2022-04-20 06:09
duplicate of https://github.com/OpenEnergyPlatform/oeplatform/issues/879, so i close it here :-)

**Closed by wingechr** 2022-04-20 06:09 UTC
Labels: bug
