### ISSUE TITLE
Invalid table names 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#320] opened 2018-10-31 14:00 UTC
When creating a table via the API, containing upper-case characters an error occurs (due to postgres restrictions). However, in the dataviewer on the platform the title of the wrongly named table was visible including an invalid link. 
![error](https://user-images.githubusercontent.com/36844029/47792966-74e8bd00-dd1d-11e8-92aa-4a1bced2c7bc.JPG)
![invalid](https://user-images.githubusercontent.com/36844029/47793037-9b0e5d00-dd1d-11e8-9ebf-3104f40d71df.JPG)

**Comment by MGlauer** [comment] 2018-11-01 07:42
This was caused by a bug inside the (invisible) data versioning and has been fixed in  608d277. I will merge this commit after some testing. Upper-case table names are not prohibited per se but violate the soft quality requirements of the oedb and, thus, should be avoided.

**Closed** 2019-12-05 12:28 UTC
Labels: SzenarienDB, bug
