### ISSUE TITLE
toep: Open Peer Review: can only work on a few items befor buttons do not react any longer

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1361] opened 2023-08-22 05:59 UTC
I have tried to review two data sets on toep.
When I worked through the first one, I could only work on the first three entries, and then the buttons "accept", "suggest", "deny" were not clickable any longer. Also when I saved the progress and opened it again, i was not able to click these any longer. 

On the second one I came further, but then the same happened and I could not continue.
These were the datasets:

- https://toep.iks.cs.ovgu.de/dataedit/view/model_draft/oeko_testtable

- https://toep.iks.cs.ovgu.de/dataedit/view/model_draft/szenarien_db_mmr

![grafik](https://github.com/OpenEnergyPlatform/oeplatform/assets/36844029/54c0ff88-8c54-4bc3-b6db-42765b1fb99b)

PS: i am not sure -

**Comment by jh-RLI** [comment] 2023-08-22 08:58
The problem is that fields that are not reviewed (no colored border) have no status and therefore cannot be evaluated after a click.

**Comment by jh-RLI** [comment] 2023-08-22 09:46
I fixed this in the linked PR. Once this is merged we will update the TOEP and you can check again if you have time :).

**Closed** 2023-08-22 11:10 UTC
Labels: bug

**Comment by jh-RLI** [comment] 2023-08-22 13:54
@han-f this problem is now fixed and the new version is available on TOEP
