### ISSUE TITLE
Name column in schema still shows filenames of tables

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#684] opened 2020-11-13 07:56 UTC
The name column in schemas, e.g. here: https://openenergy-platform.org/dataedit/view/scenario
still shows the names of the tables rather than the title. I thought we had an issue on this already, but cannot find it anymore. I think this is important to fix.

**Comment by MGlauer** [comment] 2020-11-13 09:15
Yes, this is a duplicate of #634

**Closed by MGlauer** 2020-11-13 09:15 UTC
Labels: SzenarienDB, Urgency-L, bug
