### ISSUE TITLE
[Factsheets] submitting parts of the fact sheets

### ISSUE THREAD

**Issue by EvaWie** [OpenEnergyPlatform/oeplatform#27] opened 2016-03-14 13:40 UTC
I would expect a message like "changes / fact sheet successfully saved", after clicking on submit.

Instead of being brought to the next tab, you find yourself on the first tab "general information" after submitting a part.

When does the model fact sheet appear in the list of model fact sheets. I am quite sure that it did not appear directly after submitting the first parts of the model fact sheets.

After submitting the Mathematical properties, the server error 500 occurred. The fact sheet I was working on occurred in the list of model fact sheets (but I cannot open it "server error"). When I tried to reproduce the server error by clicking on the submit button in the Mathematical properties tab, I got back to the General Information tab of the fact sheet creating page telling me "Basic factsheet [ TWO WORDS] with this Name [SHOULD BE LOWERCASE] already exists." In my opinion that messages should tell me more. Are my latest changes lost? How do I go on (e.g. editing the existing fact sheet)?

**Comment by MGlauer** [comment] 2016-03-14 19:35
It is not even possible to submit only parts of the factsheet. You are redirected to the General tab, because there are mandatory fields missing. 

I will add a token to tabs that contain errors.

**Comment by MGlauer** [comment] 2016-03-15 12:09
I added a hofix for better error messages

**Comment by christian-rli** [comment] 2021-11-01 10:26
After revision this is now a duplicate of #70

**Closed by christian-rli** 2021-11-01 10:26 UTC
Labels: Factsheets, specification_sheet
