### ISSUE TITLE
toep: scenario bundle won't save 

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/oeplatform#1464] opened 2023-11-08 11:18 UTC
## Description of the issue

I created a new scenario bundle. I successfully saved the "basic information", but any other edits seem to produce an endless "saving wheel"
## Steps to Reproduce
1. Create new scenario bundle
2. Edit basic information - > save
3. Edit an other information -> try to save

## Ideas of solution

?

## Context and Environment
* Version used: 
* Operating system: Windows 10
* Browser: Firefox

## Workflow checklist
- [ ] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/OpenEnergyPlatform/oeplatform/blob/develop/CONTRIBUTING.md)

**Comment by adelmemariani** [comment] 2023-11-08 12:56
Thank you @han-f for highlighting this issue. I reproduced the error. While the "saving weel" never ended, the bundle is saved in the background. The main reason of this error is that the update method has changed in the bundles because of the new way of storing the history of the oekg: [#1448](https://github.com/OpenEnergyPlatform/oeplatform/issues/1448). As this is a newly added feature, it is currently experiencing some bugs. I will investigate more and fix this issue. The production server is functioning properly since the "history" feature has not been applied there. Adding bundles to the real oep seems to be a good idea.

**Comment by adelmemariani** [comment] 2023-11-08 13:03
**Update**: It seems the problem is not related to the code but it is related to the Python version and the packages installed on the server.

**Comment by jh-RLI** [comment] 2023-11-08 13:16
Thanks for looking into this @adelmemariani we would need to fix this bug to deploy the release on Monday, do you think we can fix it? If it's related to the python version, we might have to remove the history updates because we can't update the python version :/

**Comment by adelmemariani** [comment] 2023-11-08 13:42
@jh-RLI I think it is related to the rdflib package, but we may need to upgrade the Python as well. I am trying to see if upgrading the pip and python is possible during the remaining time before our release.

**Comment by adelmemariani** [comment] 2023-11-08 16:47
Solved!

I changed the code to use another serialization. The bundle update now works and the modifications can be seen [here](http://toep.iks.cs.ovgu.de/scenario-bundles/oekg_modifications).

**Comment by jh-RLI** [comment] 2023-11-08 16:48
Great!!! Are there any downsides to this solution?
It would still be good if we could just update the Python version. But I don't have much hope that we will be allowed to do this.

**Comment by jh-RLI** [comment] 2023-11-08 16:50
Please also add this fix to the develop branch by creating a new branch and pull request :)

**Comment by adelmemariani** [comment] 2023-11-08 17:01
> Great!!! Are there any downsides to this solution? It would still be good if we could just update the Python version. But I don't have much hope that we will be allowed to do this.

There is no negative impact from using this method. But since we have to use RDFLib version 5.0.0 and the current version of the RDFLib is 7.0.0, we can not store the modifications as JSON-LD objects. The model.py in our Django app uses JSONField() for the modifications and since a JSON objects is not an option for us, I had to use the [NTSerializer](https://rdflib.readthedocs.io/en/5.0.0/apidocs/rdflib.plugins.serializers.html#rdflib.plugins.serializers.nt.NTSerializer) and convert the outcome to string and store them like [here](http://toep.iks.cs.ovgu.de/scenario-bundles/oekg_modifications), which might not be as readable as JSON-LD format.

**Comment by adelmemariani** [comment] 2023-11-08 17:14
I think it is a temporary solution. Storing JSON objects makes it easier to undo the changes, but currently, we store strings and it makes it difficult to extract values for rolling back the OEKG to a previous state. We should upgrade the Python in the future.

**Comment by jh-RLI** [comment] 2023-11-10 09:22
I will close this issue as the issue was solved. @adelmemariani to save some time on monday it would be great if this fix is already submitted as PR to develop branch i think there is none so far? :)

**Closed by jh-RLI** 2023-11-10 09:22 UTC
Labels: bug
